### ISSUE TITLE
How to fix this error please

### ISSUE THREAD

**Issue by YangZiz** [davidiommi/3D-CycleGan-Pytorch-MedImaging#6]
I get the following error when I run the organize_folder_structure.py:
Traceback (most recent call last):
  File "C:/Users/Desktop/code/3D-CycleGan-Pytorch-MedImaging-main/organize_folder_structure.py", line 157, in <module>
    reference_image = resample_sitk_image(reference_image, spacing=args.resolution, interpolator='linear')
  File "C:\Users\Desktop\code\3D-CycleGan-Pytorch-MedImaging-main\utils\NiftiDataset.py", line 189, in resample_sitk_image
    orig_pixelid)
TypeError: Execute() takes 2 positional arguments but 10 were given
and how should I fix it?
Thank you!

**Comment by zzx721838322** [comment]
和我一样

**Comment by Yueup** [comment]
我去**simpleITK**官方文档查了**Execute()**这个函数只有两个参数，但是NiftiDataset.py代码中给了九个参数。不知道如何解决

**Comment by zzx721838322** [comment]
我也不知道

**Comment by Yueup** [comment]
> 我也不知道

找到解决方法了，参见这个链接里面的[resample_sitk_image函数](https://github.com/davidiommi/Pytorch--3D-Medical-Images-Segmentation--SALMON/blob/master/utils.py)

**Comment by zzx721838322** [comment]
谢谢，你的代码成功运行起来了吗

**Comment by Yueup** [comment]
> 
嗯 仅就**organize_folder_structure.py**这个程序来说成功了，其他的还在调试

**Comment by zzx721838322** [comment]
好的 谢谢
